// examples/frameworks/react/src/App.js
import React, { useState, useRef, useEffect } from 'react';
import './App.css';

function App() {
  const [imageData, setImageData] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [status, setStatus] = useState('Ready');
  const [geglWorker, setGeglWorker] = useState(null);

  const canvasRef = useRef(null);
  const fileInputRef = useRef(null);

  // Initialize GEGL worker
  useEffect(() => {
    const initWorker = async () => {
      try {
        setStatus('Initializing GEGL...');
        const worker = new window.GeglWorker('../../../build-wasm-prod/gegl.js');
        await worker.init();
        setGeglWorker(worker);
        setStatus('GEGL initialized successfully');
      } catch (error) {
        console.error('Failed to initialize GEGL:', error);
        setStatus('Failed to initialize GEGL');
      }
    };

    if (window.GeglWorker) {
      initWorker();
    } else {
      setStatus('GEGL worker not loaded');
    }

    return () => {
      if (geglWorker) {
        geglWorker.cleanup();
      }
    };
  }, []);

  const handleFileSelect = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    try {
      setStatus('Loading image...');

      const img = new Image();
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
        img.src = URL.createObjectURL(file);
      });

      const canvas = canvasRef.current;
      const ctx = canvas.getContext('2d');
      canvas.width = img.width;
      canvas.height = img.height;
      ctx.drawImage(img, 0, 0);

      const imgData = ctx.getImageData(0, 0, img.width, img.height);
      setImageData(imgData);
      setStatus('Image loaded successfully');

      URL.revokeObjectURL(img.src);

    } catch (error) {
      console.error('Failed to load image:', error);
      setStatus('Failed to load image');
    }
  };

  const applyBlur = async () => {
    if (!imageData || !geglWorker) return;

    try {
      setIsProcessing(true);
      setStatus('Applying blur effect...');

      const operations = [{
        operation: 'gegl:blur-gaussian',
        properties: {
          std_dev_x: 5.0,
          std_dev_y: 5.0
        }
      }];

      const result = await geglWorker.process(imageData, operations);

      const canvas = canvasRef.current;
      const ctx = canvas.getContext('2d');
      const processedImageData = new ImageData(
        new Uint8ClampedArray(result.data),
        result.width,
        result.height
      );
      ctx.putImageData(processedImageData, 0, 0);

      setStatus('Blur effect applied successfully');

    } catch (error) {
      console.error('Failed to apply blur:', error);
      setStatus('Failed to apply blur effect');
    } finally {
      setIsProcessing(false);
    }
  };

  const resetImage = () => {
    if (imageData) {
      const canvas = canvasRef.current;
      const ctx = canvas.getContext('2d');
      ctx.putImageData(imageData, 0, 0);
      setStatus('Image reset to original');
    }
  };

  return (
    <div className="app">
      <header className="app-header">
        <h1>GEGL.wasm React Example</h1>
      </header>

      <main className="app-main">
        <div className="file-input-section">
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            onChange={handleFileSelect}
            style={{ display: 'none' }}
          />
          <button
            className="file-button"
            onClick={() => fileInputRef.current.click()}
          >
            Select Image
          </button>
        </div>

        <div className="canvas-section">
          <canvas ref={canvasRef} className="image-canvas" />
        </div>

        <div className="controls-section">
          <button
            onClick={applyBlur}
            disabled={!imageData || isProcessing || !geglWorker}
            className="control-button"
          >
            {isProcessing ? 'Processing...' : 'Apply Blur'}
          </button>
          <button
            onClick={resetImage}
            disabled={!imageData}
            className="control-button"
          >
            Reset
          </button>
        </div>

        <div className="status-section">
          <p>{status}</p>
        </div>
      </main>
    </div>
  );
}

export default App;

// examples/frameworks/angular/src/app/app.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef } from '@angular/core';

declare var GeglWorker: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnDestroy {
  title = 'GEGL Angular Example';

  @ViewChild('fileInput', { static: true }) fileInput!: ElementRef<HTMLInputElement>;
  @ViewChild('canvas', { static: true }) canvas!: ElementRef<HTMLCanvasElement>;

  imageData: ImageData | null = null;
  isProcessing = false;
  status = 'Ready';
  geglWorker: any = null;

  async ngOnInit() {
    if ((window as any).GeglWorker) {
      try {
        this.status = 'Initializing GEGL...';
        this.geglWorker = new (window as any).GeglWorker('../../../build-wasm-prod/gegl.js');
        await this.geglWorker.init();
        this.status = 'GEGL initialized successfully';
      } catch (error) {
        console.error('Failed to initialize GEGL:', error);
        this.status = 'Failed to initialize GEGL';
      }
    } else {
      this.status = 'GEGL worker not loaded';
    }
  }

  ngOnDestroy() {
    if (this.geglWorker) {
      this.geglWorker.cleanup();
    }
  }

  selectFile() {
    this.fileInput.nativeElement.click();
  }

  async onFileSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;

    try {
      this.status = 'Loading image...';

      const img = new Image();
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
        img.src = URL.createObjectURL(file);
      });

      const ctx = this.canvas.nativeElement.getContext('2d')!;
      this.canvas.nativeElement.width = img.width;
      this.canvas.nativeElement.height = img.height;
      ctx.drawImage(img, 0, 0);

      this.imageData = ctx.getImageData(0, 0, img.width, img.height);
      this.status = 'Image loaded successfully';

      URL.revokeObjectURL(img.src);

    } catch (error) {
      console.error('Failed to load image:', error);
      this.status = 'Failed to load image';
    }
  }

  async applyBlur() {
    if (!this.imageData || !this.geglWorker) return;

    try {
      this.isProcessing = true;
      this.status = 'Applying blur effect...';

      const operations = [{
        operation: 'gegl:blur-gaussian',
        properties: {
          std_dev_x: 5.0,
          std_dev_y: 5.0
        }
      }];

      const result = await this.geglWorker.process(this.imageData, operations);

      const ctx = this.canvas.nativeElement.getContext('2d')!;
      const processedImageData = new ImageData(
        new Uint8ClampedArray(result.data),
        result.width,
        result.height
      );
      ctx.putImageData(processedImageData, 0, 0);

      this.status = 'Blur effect applied successfully';

    } catch (error) {
      console.error('Failed to apply blur:', error);
      this.status = 'Failed to apply blur effect';
    } finally {
      this.isProcessing = false;
    }
  }

  resetImage() {
    if (this.imageData) {
      const ctx = this.canvas.nativeElement.getContext('2d')!;
      ctx.putImageData(this.imageData, 0, 0);
      this.status = 'Image reset to original';
    }
  }
}
<div class="app">
  <header class="app-header">
    <h1>{{ title }}</h1>
  </header>

  <main class="app-main">
    <div class="file-input-section">
      <input
        #fileInput
        type="file"
        accept="image/*"
        (change)="onFileSelected($event)"
        style="display: none"
      />
      <button class="file-button" (click)="selectFile()">
        Select Image
      </button>
    </div>

    <div class="canvas-section">
      <canvas #canvas class="image-canvas"></canvas>
    </div>

    <div class="controls-section">
      <button
        (click)="applyBlur()"
        [disabled]="!imageData || isProcessing || !geglWorker"
        class="control-button"
      >
        {{ isProcessing ? 'Processing...' : 'Apply Blur' }}
      </button>
      <button
        (click)="resetImage()"
        [disabled]="!imageData"
        class="control-button"
      >
        Reset
      </button>
    </div>

    <div class="status-section">
      <p>{{ status }}</p>
    </div>
  </main>
</div>
